[package]
name = "ssh-agent-lib"
description = "A collection of types for writing custom SSH agents"
version = "0.2.3"
license = "MIT"
authors = [
    "Nicolas Trippar <ntrippar@gmail.com>",
    "Federico Pomar <fmpomar@users.noreply.github.com>",
    "Wiktor Kwapisiewicz <wiktor@metacode.biz>"
]
repository = "https://github.com/wiktor-k/ssh-agent.rs"
edition = "2021"

[dependencies]
byteorder = "1.4"
serde = {version = "1", features = ["derive"]}

bytes = { version = "1.1", optional = true }
#futures = { version = "0.1.25", optional = true }
futures = { version = "0.3.30", optional = true }
log = { version = "0.4.16", optional = true }
tokio = { version = "1", optional = true, features = ["rt", "net", "rt-multi-thread"] }
tokio-util = { version = "0.7", optional = true, features = ["codec"] }
tokio-stream = { version = "0.1.14", optional = true, features = ["net"] }
#tokio-uds = { version = "0.2.5", optional = true }

[features]
default = ["agent"]
agent = ["log", "tokio", "tokio-util", "bytes", "futures", "tokio-stream"]

[[example]]
name = "key_storage"
required-features = ["agent"]
