[package]
name = "ssh-agent-lib"
description = "A collection of types for writing custom SSH agents"
version = "0.4.0"
license = "MIT"
authors = [
    "Nicolas Trippar <ntrippar@gmail.com>",
    "Federico Pomar <fmpomar@users.noreply.github.com>",
    "Wiktor Kwapisiewicz <wiktor@metacode.biz>"
]
repository = "https://github.com/wiktor-k/ssh-agent-lib"
edition = "2021"
keywords = ["ssh", "agent", "authentication", "openssh", "async"]
categories = ["authentication", "cryptography", "encoding", "network-programming", "parsing"]
exclude = [".github"]

[dependencies]
byteorder = "1.4.3"
async-trait = { version = "0.1.77", optional = true }
futures = { version = "0.3.30", optional = true }
log = { version = "0.4.6", optional = true }
tokio = { version = "1", optional = true, features = ["rt", "net"] }
tokio-util = { version = "0.7.1", optional = true, features = ["codec"] }
service-binding = { version = "^2" }
ssh-encoding = { version = "0.2.0" }
ssh-key = { version = "0.6.4", features = ["rsa", "alloc"] }

[features]
default = ["agent"]
agent = ["futures", "log", "tokio", "tokio-util", "async-trait"]

[[example]]
name = "key_storage"
required-features = ["agent"]

[dev-dependencies]
env_logger = "0.11.0"
rand = "0.8.5"
rsa = { version = "0.9.6", features = ["sha2", "sha1"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
sha1 = { version = "0.10.5", default-features = false, features = ["oid"] }
testresult = "0.4.0"
hex-literal = "0.4.1"
ssh-key = { version = "0.6.4", features = ["p256"] }
p256 = { version = "0.13.2" }
const-str = "0.5.7"
